version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=exampleApp
      - POSTGRES_PASSWORD=verySecurePassword
      
    ports:
      - '5433:5432'
    volumes: 
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    
volumes:
  data:
  init_sql: