version: '3'


networks:
  app_net:
    name: app_net

services:

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_net
  kafka:

  
    image: docker.io/bitnami/kafka:3.4
    
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,PLAINTEXT://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,PLAINTEXT://kafka:9091
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    
    ports:
     - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app_net


  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=exampleApp
      - POSTGRES_PASSWORD=verySecurePassword
      
    ports:
      - '5433:5432'
    volumes: 
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    
volumes:
  data:
  init_sql:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local